name: Cleanup SonarQube PR Project

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - delete-me

jobs:
  cleanup-sonarqube:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract base sonar.projectKey
        id: basekey
        run: |
          BASE_KEY=$(grep '^sonar.projectKey=' sonar-project.properties | cut -d'=' -f2)
          if [[ -z "$BASE_KEY" ]]; then
            echo "sonar.projectKey not found in sonar-project.properties"
            exit 1
          fi
          echo "base_key=$BASE_KEY" >> "$GITHUB_OUTPUT"

      - name: Sanitize merged branch name
        id: branch
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          BRANCH_KEY=$(echo "$BRANCH_NAME" | tr '/' '-' | tr -cd '[:alnum:]-')
          echo "name=$BRANCH_KEY" >> "$GITHUB_OUTPUT"

      - name: Delete SonarQube PR project
        run: |
          PR_PROJECT_KEY="${{ steps.basekey.outputs.base_key }}-pr-${{ steps.branch.outputs.name }}"
          echo "Deleting SonarQube project: $PR_PROJECT_KEY"

          response=$(curl -s -H "Authorization: Bearer ${{ secrets.SONAR_ADMIN_TOKEN }}" \
            "https://sonarqube.populationgenomics.org.au/api/projects/search?projects=${PR_PROJECT_KEY}")

          if [ "$response" -eq 204 ]; then
            echo "Project $PR_PROJECT_KEY deleted successfully."
          else
            echo "Failed to delete project $PR_PROJECT_KEY. HTTP status: $response"
            cat response.txt
          fi
