name: Hail Batch Job Workflow

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  hail-batch-job:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - id: "google-cloud-auth"
        name: "Authenticate to Google Cloud"
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/1051897107465/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "gh-artifact-registry-reader@cpg-common.iam.gserviceaccount.com"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install hail

      - name: Submit and Monitor Hail Batch Job
        env:
          TMP_DIR: ${{ env.TMPDIR }}
        run: python tests/hail/workflow.py
