name: Lint
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          uv-version: "0.4.22"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install pre-commit from dev dependencies
        run: uv sync --only-dev

      - name: Install pre-commit hooks
        run: uv run pre-commit install --install-hooks

      - name: Run pre-commit
        run: uv run pre-commit run --all-files
