name: Lint
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          # Install a specific version of uv.
          version: '0.4.22'

      - name: Set up Python
        run: uv python install

      - name: Install the dependencies
        run: uv sync --all-extras --dev

      - name: Install pre-commit hooks
        # For example, using `pytest`
        run: uv run pre-commit install --install-hooks

      - name: Run pre-commit
        run: uv run pre-commit run --all-files
