name: Update Badges
on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  update_badges:
    name: Update Badges
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_commit.id }}
          repository: ${{ github.event.workflow_run.head_repository.full_name }}

      - name: "Update badges.yaml"
        run: |
          cat <<EOF > docs/badges.yaml
          test-badge:
            status: ${{ github.event.workflow_run.output.TEST_PASSED }} / ${{ github.event.workflow_run.output.TEST_COUNT }} passed
            color: ${{ github.event.workflow_run.output.TEST_COLOR }}
          coverage-badge:
            status: ${{ github.event.workflow_run.output.COVERAGE }}
            color: ${{ github.event.workflow_run.output.COVERAGE_COLOR }}
          EOF

      - name: "Commit and Push Changes"
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/badges.yaml
          git commit -m "chore: update badges.yaml with test results and coverage"
          git push
